//propinsi
export const DELETE_PROPINSI_REQUEST = 'DELETE_PROPINSI_REQUEST';
export const DELETE_PROPINSI_SUCCESS = 'DELETE_PROPINSI_SUCCESS';
export const DELETE_PROPINSI_FAILURE = 'DELETE_PROPINSI_FAILURE';

export const FIND_PROPINSI_REQUEST = 'FIND_PROPINSI_REQUEST';
export const FIND_PROPINSI_SUCCESS = 'FIND_PROPINSI_SUCCESS';
export const FIND_PROPINSI_FAILURE = 'FIND_PROPINSI_FAILURE';

export const FIND_PROPINSIS_REQUEST = 'FIND_PROPINSIS_REQUEST';
export const FIND_PROPINSIS_SUCCESS = 'FIND_PROPINSIS_SUCCESS';
export const FIND_PROPINSIS_FAILURE = 'FIND_PROPINSIS_FAILURE';

export const ADD_PROPINSI_REQUEST = 'ADD_PROPINSI_REQUEST';
export const ADD_PROPINSI_SUCCESS = 'ADD_PROPINSI_SUCCESS';
export const ADD_PROPINSI_FAILURE = 'ADD_PROPINSI_FAILURE';

export const UPDATE_PROPINSI_REQUEST = 'UPDATE_PROPINSI_REQUEST';
export const UPDATE_PROPINSI_SUCCESS = 'UPDATE_PROPINSI_SUCCESS';
export const UPDATE_PROPINSI_FAILURE = 'UPDATE_PROPINSI_FAILURE';

//kontrasepsi
export const DELETE_KONTRASEPSI_REQUEST = 'DELETE_KONTRASEPSI_REQUEST';
export const DELETE_KONTRASEPSI_SUCCESS = 'DELETE_KONTRASEPSI_SUCCESS';
export const DELETE_KONTRASEPSI_FAILURE = 'DELETE_KONTRASEPSI_FAILURE';

export const FIND_KONTRASEPSI_REQUEST = 'FIND_KONTRASEPSI_REQUEST';
export const FIND_KONTRASEPSI_SUCCESS = 'FIND_KONTRASEPSI_SUCCESS';
export const FIND_KONTRASEPSI_FAILURE = 'FIND_KONTRASEPSI_FAILURE';

export const FIND_KONTRASEPSIS_REQUEST = 'FIND_KONTRASEPSIS_REQUEST';
export const FIND_KONTRASEPSIS_SUCCESS = 'FIND_KONTRASEPSIS_SUCCESS';
export const FIND_KONTRASEPSIS_FAILURE = 'FIND_KONTRASEPSIS_FAILURE';

export const ADD_KONTRASEPSI_REQUEST = 'ADD_KONTRASEPSI_REQUEST';
export const ADD_KONTRASEPSI_SUCCESS = 'ADD_KONTRASEPSI_SUCCESS';
export const ADD_KONTRASEPSI_FAILURE = 'ADD_KONTRASEPSI_FAILURE';

export const UPDATE_KONTRASEPSI_REQUEST = 'UPDATE_KONTRASEPSI_REQUEST';
export const UPDATE_KONTRASEPSI_SUCCESS = 'UPDATE_KONTRASEPSI_SUCCESS';
export const UPDATE_KONTRASEPSI_FAILURE = 'UPDATE_KONTRASEPSI_FAILURE';

//pemakai
export const DELETE_PEMAKAI_REQUEST = 'DELETE_PEMAKAI_REQUEST';
export const DELETE_PEMAKAI_SUCCESS = 'DELETE_PEMAKAI_SUCCESS';
export const DELETE_PEMAKAI_FAILURE = 'DELETE_PEMAKAI_FAILURE';

export const FIND_PEMAKAI_REQUEST = 'FIND_PEMAKAI_REQUEST';
export const FIND_PEMAKAI_SUCCESS = 'FIND_PEMAKAI_SUCCESS';
export const FIND_PEMAKAI_FAILURE = 'FIND_PEMAKAI_FAILURE';

export const FIND_PEMAKAIS_REQUEST = 'FIND_PEMAKAIS_REQUEST';
export const FIND_PEMAKAIS_SUCCESS = 'FIND_PEMAKAIS_SUCCESS';
export const FIND_PEMAKAIS_FAILURE = 'FIND_PEMAKAIS_FAILURE';

export const ADD_PEMAKAI_REQUEST = 'ADD_PEMAKAI_REQUEST';
export const ADD_PEMAKAI_SUCCESS = 'ADD_PEMAKAI_SUCCESS';
export const ADD_PEMAKAI_FAILURE = 'ADD_PEMAKAI_FAILURE';

export const UPDATE_PEMAKAI_REQUEST = 'UPDATE_PEMAKAI_REQUEST';
export const UPDATE_PEMAKAI_SUCCESS = 'UPDATE_PEMAKAI_SUCCESS';
export const UPDATE_PEMAKAI_FAILURE = 'UPDATE_PEMAKAI_FAILURE';
